# Generated by Django 5.2.1 on 2025-06-23 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_main_image_product_price_delete_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisan',
            name='workshop_photos',
        ),
        migrations.AddField(
            model_name='artisan',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='artisans/'),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artisans', to='shop.region'),
        ),
        migrations.DeleteModel(
            name='ArtisanPhoto',
        ),
    ]
