# Generated by Django 5.2.1 on 2025-06-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_artisan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
