# Generated by Django 5.2.1 on 2025-06-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_artisan_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='phone',
            field=models.CharField(default='0661889014', max_length=20),
            preserve_default=False,
        ),
    ]
